location = "eastus"
resource_group_name = "HelloCloud"
vnet_cidr = "10.0.0.0/16"
subnet1_cidr = "10.0.2.0/24"
vm_username = "azureuser"
vm_password = "MyPassword14+"
environment = "dev"
storage_account_name = "azurehellocloud007"